create database SYC

use SYC

/****** CREAR TABLA FACTURA ******/
CREATE TABLE FACTURA (
	ID_FACTURA numeric (18,0) primary key not null,
	NUME_DOC numeric (18,0) not null,
	CODI_ESTADO numeric (2,0) not null,
	VALOR_FAC numeric (18,0) not null,
	FECHA_FAC datetime not null
);

/****** CREAR TABLA CLIENTES ******/

create table CLIENTES(
	NUME_DOC numeric(18,0) primary key not null,
	NOMBRE varchar(200) not null,
	DIRECCION varchar (200) not null
);
/****** CREAR TABLA ESTADOS FACTURA ******/
create table ESTADOS_FACTURA(
	CODI_ESTADO numeric(2,0) primary key not null,
	DESCRIPCION varchar(20) 
);

ALTER TABLE FACTURA
ADD FOREIGN KEY (NUME_DOC) REFERENCES CLIENTES(NUME_DOC);

ALTER TABLE FACTURA
ADD FOREIGN KEY (CODI_ESTADO) REFERENCES ESTADOS_FACTURA(CODI_ESTADO); 


create procedure sp_Listar
as
begin
	select * from FACTURA
end

create procedure sp_Guardar(
@ID_FACTURA numeric(18,0),
@NUME_DOC numeric(18,0),
@CODI_ESTADO numeric(18,0),
@VALOR_FAC numeric(18,0),
@FECHA_FAC datetime
)
as
begin
	insert into FACTURA(ID_FACTURA,NUME_DOC,CODI_ESTADO,VALOR_FAC,FECHA_FAC) values (@ID_FACTURA,@NUME_DOC,@CODI_ESTADO,@VALOR_FAC,@FECHA_FAC) 
end

create procedure sp_Reporte
as
begin
	SELECT FACTURA.FECHA_FAC,CLIENTES.NOMBRE,SUM(FACTURA.VALOR_FAC) AS VALOR_FAC, ESTADOS_FACTURA.DESCRIPCION
	FROM FACTURA
	INNER JOIN CLIENTES ON FACTURA.NUME_DOC=CLIENTES.NUME_DOC
	INNER JOIN ESTADOS_FACTURA ON FACTURA.CODI_ESTADO=ESTADOS_FACTURA.CODI_ESTADO
	GROUP BY FACTURA.FECHA_FAC, CLIENTES.NOMBRE, ESTADOS_FACTURA.DESCRIPCION
end

-- CREAR DATOS DE ESTADOS_FACTURA
INSERT INTO ESTADOS_FACTURA(CODI_ESTADO, DESCRIPCION)
VALUES (1,'VIGENTE');
INSERT INTO ESTADOS_FACTURA(CODI_ESTADO, DESCRIPCION)
VALUES (2,'PAGADA');
INSERT INTO ESTADOS_FACTURA(CODI_ESTADO, DESCRIPCION)
VALUES (3,'VENCIDA');

-- CREAR DATOS DE CLIENTES
INSERT INTO CLIENTES(NUME_DOC, NOMBRE,DIRECCION)
VALUES (1102384340,'STEVE JOBS','Altavista');
INSERT INTO CLIENTES(NUME_DOC, NOMBRE,DIRECCION)
VALUES (1102384341,'LINUS TORVALDS','BOGOTA');
INSERT INTO CLIENTES(NUME_DOC, NOMBRE,DIRECCION)
VALUES (1102384342,'JON DOE','CUCUTA');
INSERT INTO CLIENTES(NUME_DOC, NOMBRE,DIRECCION)
VALUES (1102384343,'BILL GATES','Altavista');
INSERT INTO CLIENTES(NUME_DOC, NOMBRE,DIRECCION)
VALUES (1102384344,'FABIAN JOBS','PAIPA');